name: Validate Kubernetes Manifests

on:
  workflow_call:

jobs:
  validate-kustomizations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate manifests
      run: |
        kustomization_dirs=$(find . -type f -name 'kustomization.yaml' -exec dirname {} \; | sed 's|^\./||')

        if [[ -z "${kustomization_dirs}" ]]; then
          echo "No kustomization.yaml files found."
          exit 0
        fi

        while read dir; do
          echo "Validating kustomization in directory: ${dir}"

          kubectl kustomize "${dir}" --enable-helm
        done <<< "${kustomization_dirs}"

  validate-helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Helm validation
      run: |
        helm_dirs=$(find . -type f -name 'Chart.yaml' -exec dirname {} \; | sed 's|^\./||')

        if [[ -z "${helm_dirs}" ]]; then
          echo "No Chart.yaml files found."
          exit 0
        fi

        while read dir; do
          echo "Validating helm in directory: ${dir}"

          helm lint "${dir}"
          (cd "${dir}" && helm dependency build)
          helm template "${dir}" -f "${dir}/values.yaml"
        done <<< "${helm_dirs}"
